### PR TITLE
Remove redundant "is"

### PR DESCRIPTION
**Pull request by akanshgulati**

### CODE REVIEW

**Review by yoavweiss — APPROVED** [review]
LGTM.
Thanks for catching that typo!

**Comment by yoavweiss** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by npm1** [comment]
It wasn't a typo... "While the main content is important to the user experience, what the main content is is highly subjective and different users can come up with different answers."

Now the sentence doesn't make sense: "While the main content is important to the user experience, what the main content is highly subjective and different users can come up with different answers."

The double is can be confusing (we can use a different word to replace the first one), but it was correct.

**Comment by yoavweiss** [comment]
Apologies! Reverting

**Comment by yoavweiss** [comment]
Might be worthwhile to reword to make the sentence less confusing...

**Comment by npm1** [comment]
Agreed, @akanshgulati do you want to take a stab at it or I can send something your way to review?

**Comment by akanshgulati** [comment]
@npm1 How about 
"While the main content is important to the user experience, but it is highly subjective and different users can come up with different answers."

**Comment by npm1** [comment]
Sounds good, modulo removing the 'but'. Thanks for the suggestion!

**Pull request merged**
