### PR TITLE
Fix Bikeshed markup of request's URL

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
I hope PR preview is enabled on this repo, I made the edit without testing :)

**Comment by yoavweiss** [comment]
I fixed it independently (but in an uglier way) in #22

**Comment by yoavweiss** [comment]
Closing because this is fixed in #22

**Comment by yoavweiss** [comment]
(But thanks for PRing a fix in the first place :D)

**Pull request closed without merging**
